[build]
  command = "pip install --upgrade pip setuptools wheel && pip install -r requirements.txt"
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.11"
  PIP_UPGRADE = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200