[build]
  command = "echo 'Static deployment - no build needed'"
  publish = "static"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF"

[build.environment]
  NPM_FLAGS = "--production=false"
  SKIP_DEPENDENCY_INSTALL = "true"
  NETLIFY_SKIP_PYTHON_BUILD = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200