[build]
  command = "echo 'This is a Flask app that requires a Python server. Please deploy to Render, Railway, or Heroku instead.'"
  publish = "static"

[build.environment]
  PYTHON_VERSION = "3.11"